// icons.js

ICONNAMES = [
  'text-primary oi oi-ban',
  'text-primary oi oi-bell',
  'text-primary oi oi-briefcase',
  'text-primary oi oi-bug',
  'text-primary oi oi-heart',
  'text-primary oi oi-camera-slr',
  'text-primary oi oi-cog',
  'text-primary oi oi-command',
  'text-primary oi oi-envelope-closed',
  'text-primary oi oi-headphones',
  'text-primary oi oi-heart',
  'text-primary oi oi-image',
  'text-primary oi oi-key',
  'text-primary oi oi-lock-locked',
  'text-primary oi oi-map-marker',
  'text-primary oi oi-medical-cross',
  'text-primary oi oi-microphone',
  'text-primary oi oi-moon',
  'text-primary oi oi-musical-note',
  'text-primary oi oi-phone',
  'text-primary oi oi-rain',
  'text-primary oi oi-rss',
  'text-primary oi oi-sun',
  'text-primary oi oi-shield',
  'text-primary oi oi-tablet',
  'text-primary oi oi-target',
  'text-primary oi oi-trash',
  'text-primary oi oi-volume-high',
  'text-primary oi oi-wifi',
  'text-primary oi oi-wrench',
  'text-primary oi oi-x'
];